easy_admin:
    entities:
#        User:
#            class: App\Entity\User
#            form:
#                fields:
#                  - username
#                  - email
#                  - enabled
#                  - lastLogin
#                  # if administrators are allowed to edit users' passwords and roles, add this:
#                  - { property: 'plainPassword', type: 'text', type_options: { required: false } }
#                  - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

        # List the entity class name you want to manage
        - App\Entity\Event
    site_name: 'Event Manger'
    design:
        menu:
            # only users with the ROLE_SUPER_ADMIN role will see this menu item
#            - { entity: 'Event', permission: 'ROLE_SUPER_ADMIN' }