version: '3.7'
services:
  db:
    image: mysql:5.7.22
    ports:
      - "3306:3306"
#    volumes:
#       - dbdata:/var/lib/mysql
#       - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acid21
      MYSQL_ROOT_HOST: "%"


  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./:/usr/src/app
    user: '1000'
    links:
      - db

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    depends_on:
      - php


  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8080:8080

#Volumes

#volumes:
#  dbdata:
#    driver: local



#  phpmyadmin:
#    depends_on:
#      - db
#    image: phpmyadmin/phpmyadmin
#    restart: always
#    ports:
#      - 8088:80
#    environment:
#      PMA_HOST: db
#      MYSQL_ROOT_PASSWORD: 123456
