# app/config/config_test.yml
doctrine:
  dbal:
    default_connection: default
    connections:
      default:
        driver:   pdo_sqlite
        memory:   true
        path:     %kernel.cache_dir%/test.db